<?php


return [
    'currency_list' => [
            "AFA" => array("name" => "Afghan Afghani", "symbol" => "؋"),
            "ALL" => array("name" => "Albanian Lek", "symbol" => "Lek"),
            "DZD" => array("name" => "Algerian Dinar", "symbol" => "دج"),
            "AOA" => array("name" => "Angolan Kwanza", "symbol" => "Kz"),
            "ARS" => array("name" => "Argentine Peso", "symbol" => "$"),
            "AMD" => array("name" => "Armenian Dram", "symbol" => "֏"),
            "AWG" => array("name" => "Aruban Florin", "symbol" => "ƒ"),
            "AUD" => array("name" => "Australian Dollar", "symbol" => "$"),
            "AZN" => array("name" => "Azerbaijani Manat", "symbol" => "m"),
            "BSD" => array("name" => "Bahamian Dollar", "symbol" => "B$"),
            "BHD" => array("name" => "Bahraini Dinar", "symbol" => ".د.ب"),
            "BDT" => array("name" => "Bangladeshi Taka", "symbol" => "৳"),
            "BBD" => array("name" => "Barbadian Dollar", "symbol" => "Bds$"),
            "BYR" => array("name" => "Belarusian Ruble", "symbol" => "Br"),
            "BEF" => array("name" => "Belgian Franc", "symbol" => "fr"),
            "BZD" => array("name" => "Belize Dollar", "symbol" => "$"),
            "BMD" => array("name" => "Bermudan Dollar", "symbol" => "$"),
            "BTN" => array("name" => "Bhutanese Ngultrum", "symbol" => "Nu."),
            "BTC" => array("name" => "Bitcoin", "symbol" => "฿"),
            "BOB" => array("name" => "Bolivian Boliviano", "symbol" => "Bs."),
            "BAM" => array("name" => "Bosnia-Herzegovina Convertible Mark", "symbol" => "KM"),
            "BWP" => array("name" => "Botswanan Pula", "symbol" => "P"),
            "BRL" => array("name" => "Brazilian Real", "symbol" => "R$"),
            "GBP" => array("name" => "British Pound Sterling", "symbol" => "£"),
            "BND" => array("name" => "Brunei Dollar", "symbol" => "B$"),
            "BGN" => array("name" => "Bulgarian Lev", "symbol" => "Лв."),
            "BIF" => array("name" => "Burundian Franc", "symbol" => "FBu"),
            "KHR" => array("name" => "Cambodian Riel", "symbol" => "KHR"),
            "CAD" => array("name" => "Canadian Dollar", "symbol" => "$"),
            "CVE" => array("name" => "Cape Verdean Escudo", "symbol" => "$"),
            "KYD" => array("name" => "Cayman Islands Dollar", "symbol" => "$"),
            "XOF" => array("name" => "CFA Franc BCEAO", "symbol" => "CFA"),
            "XAF" => array("name" => "CFA Franc BEAC", "symbol" => "FCFA"),
            "XPF" => array("name" => "CFP Franc", "symbol" => "₣"),
            "CLP" => array("name" => "Chilean Peso", "symbol" => "$"),
            "CLF" => array("name" => "Chilean Unit of Account", "symbol" => "CLF"),
            "CNY" => array("name" => "Chinese Yuan", "symbol" => "¥"),
            "COP" => array("name" => "Colombian Peso", "symbol" => "$"),
            "KMF" => array("name" => "Comorian Franc", "symbol" => "CF"),
            "CDF" => array("name" => "Congolese Franc", "symbol" => "FC"),
            "CRC" => array("name" => "Costa Rican Colón", "symbol" => "₡"),
            "HRK" => array("name" => "Croatian Kuna", "symbol" => "kn"),
            "CUC" => array("name" => "Cuban Convertible Peso", "symbol" => "$, CUC"),
            "CZK" => array("name" => "Czech Republic Koruna", "symbol" => "Kč"),
            "DKK" => array("name" => "Danish Krone", "symbol" => "Kr."),
            "DJF" => array("name" => "Djiboutian Franc", "symbol" => "Fdj"),
            "DOP" => array("name" => "Dominican Peso", "symbol" => "$"),
            "XCD" => array("name" => "East Caribbean Dollar", "symbol" => "$"),
            "EGP" => array("name" => "Egyptian Pound", "symbol" => "ج.م"),
            "ERN" => array("name" => "Eritrean Nakfa", "symbol" => "Nfk"),
            "EEK" => array("name" => "Estonian Kroon", "symbol" => "kr"),
            "ETB" => array("name" => "Ethiopian Birr", "symbol" => "Nkf"),
            "EUR" => array("name" => "Euro", "symbol" => "€"),
            "FKP" => array("name" => "Falkland Islands Pound", "symbol" => "£"),
            "FJD" => array("name" => "Fijian Dollar", "symbol" => "FJ$"),
            "GMD" => array("name" => "Gambian Dalasi", "symbol" => "D"),
            "GEL" => array("name" => "Georgian Lari", "symbol" => "ლ"),
            "DEM" => array("name" => "German Mark", "symbol" => "DM"),
            "GHS" => array("name" => "Ghanaian Cedi", "symbol" => "GH₵"),
            "GIP" => array("name" => "Gibraltar Pound", "symbol" => "£"),
            "GRD" => array("name" => "Greek Drachma", "symbol" => "₯, Δρχ, Δρ"),
            "GTQ" => array("name" => "Guatemalan Quetzal", "symbol" => "Q"),
            "GNF" => array("name" => "Guinean Franc", "symbol" => "FG"),
            "GYD" => array("name" => "Guyanaese Dollar", "symbol" => "$"),
            "HTG" => array("name" => "Haitian Gourde", "symbol" => "G"),
            "HNL" => array("name" => "Honduran Lempira", "symbol" => "L"),
            "HKD" => array("name" => "Hong Kong Dollar", "symbol" => "$"),
            "HUF" => array("name" => "Hungarian Forint", "symbol" => "Ft"),
            "ISK" => array("name" => "Icelandic Króna", "symbol" => "kr"),
            "INR" => array("name" => "Indian Rupee", "symbol" => "₹"),
            "IDR" => array("name" => "Indonesian Rupiah", "symbol" => "Rp"),
            "IRR" => array("name" => "Iranian Rial", "symbol" => "﷼"),
            "IQD" => array("name" => "Iraqi Dinar", "symbol" => "د.ع"),
            "ILS" => array("name" => "Israeli New Sheqel", "symbol" => "₪"),
            "ITL" => array("name" => "Italian Lira", "symbol" => "L,£"),
            "JMD" => array("name" => "Jamaican Dollar", "symbol" => "J$"),
            "JPY" => array("name" => "Japanese Yen", "symbol" => "¥"),
            "JOD" => array("name" => "Jordanian Dinar", "symbol" => "ا.د"),
            "KZT" => array("name" => "Kazakhstani Tenge", "symbol" => "лв"),
            "KES" => array("name" => "Kenyan Shilling", "symbol" => "KSh"),
            "KWD" => array("name" => "Kuwaiti Dinar", "symbol" => "ك.د"),
            "KGS" => array("name" => "Kyrgystani Som", "symbol" => "лв"),
            "LAK" => array("name" => "Laotian Kip", "symbol" => "₭"),
            "LVL" => array("name" => "Latvian Lats", "symbol" => "Ls"),
            "LBP" => array("name" => "Lebanese Pound", "symbol" => "£"),
            "LSL" => array("name" => "Lesotho Loti", "symbol" => "L"),
            "LRD" => array("name" => "Liberian Dollar", "symbol" => "$"),
            "LYD" => array("name" => "Libyan Dinar", "symbol" => "د.ل"),
            "LTC" => array("name" => "Litecoin", "symbol" => "Ł"),
            "LTL" => array("name" => "Lithuanian Litas", "symbol" => "Lt"),
            "MOP" => array("name" => "Macanese Pataca", "symbol" => "$"),
            "MKD" => array("name" => "Macedonian Denar", "symbol" => "ден"),
            "MGA" => array("name" => "Malagasy Ariary", "symbol" => "Ar"),
            "MWK" => array("name" => "Malawian Kwacha", "symbol" => "MK"),
            "MYR" => array("name" => "Malaysian Ringgit", "symbol" => "RM"),
            "MVR" => array("name" => "Maldivian Rufiyaa", "symbol" => "Rf"),
            "MRO" => array("name" => "Mauritanian Ouguiya", "symbol" => "MRU"),
            "MUR" => array("name" => "Mauritian Rupee", "symbol" => "₨"),
            "MXN" => array("name" => "Mexican Peso", "symbol" => "$"),
            "MDL" => array("name" => "Moldovan Leu", "symbol" => "L"),
            "MNT" => array("name" => "Mongolian Tugrik", "symbol" => "₮"),
            "MAD" => array("name" => "Moroccan Dirham", "symbol" => "MAD"),
            "MZM" => array("name" => "Mozambican Metical", "symbol" => "MT"),
            "MMK" => array("name" => "Myanmar Kyat", "symbol" => "K"),
            "NAD" => array("name" => "Namibian Dollar", "symbol" => "$"),
            "NPR" => array("name" => "Nepalese Rupee", "symbol" => "₨"),
            "ANG" => array("name" => "Netherlands Antillean Guilder", "symbol" => "ƒ"),
            "TWD" => array("name" => "New Taiwan Dollar", "symbol" => "$"),
            "NZD" => array("name" => "New Zealand Dollar", "symbol" => "$"),
            "NIO" => array("name" => "Nicaraguan Córdoba", "symbol" => "C$"),
            "NGN" => array("name" => "Nigerian Naira", "symbol" => "₦"),
            "KPW" => array("name" => "North Korean Won", "symbol" => "₩"),
            "NOK" => array("name" => "Norwegian Krone", "symbol" => "kr"),
            "OMR" => array("name" => "Omani Rial", "symbol" => ".ع.ر"),
            "PKR" => array("name" => "Pakistani Rupee", "symbol" => "₨"),
            "PAB" => array("name" => "Panamanian Balboa", "symbol" => "B/."),
            "PGK" => array("name" => "Papua New Guinean Kina", "symbol" => "K"),
            "PYG" => array("name" => "Paraguayan Guarani", "symbol" => "₲"),
            "PEN" => array("name" => "Peruvian Nuevo Sol", "symbol" => "S/."),
            "PHP" => array("name" => "Philippine Peso", "symbol" => "₱"),
            "PLN" => array("name" => "Polish Zloty", "symbol" => "zł"),
            "QAR" => array("name" => "Qatari Rial", "symbol" => "ق.ر"),
            "RON" => array("name" => "Romanian Leu", "symbol" => "lei"),
            "RUB" => array("name" => "Russian Ruble", "symbol" => "₽"),
            "RWF" => array("name" => "Rwandan Franc", "symbol" => "FRw"),
            "SVC" => array("name" => "Salvadoran Colón", "symbol" => "₡"),
            "WST" => array("name" => "Samoan Tala", "symbol" => "SAT"),
            "STD" => array("name" => "São Tomé and Príncipe Dobra", "symbol" => "Db"),
            "SAR" => array("name" => "Saudi Riyal", "symbol" => "﷼"),
            "RSD" => array("name" => "Serbian Dinar", "symbol" => "din"),
            "SCR" => array("name" => "Seychellois Rupee", "symbol" => "SRe"),
            "SLL" => array("name" => "Sierra Leonean Leone", "symbol" => "Le"),
            "SGD" => array("name" => "Singapore Dollar", "symbol" => "$"),
            "SKK" => array("name" => "Slovak Koruna", "symbol" => "Sk"),
            "SBD" => array("name" => "Solomon Islands Dollar", "symbol" => "Si$"),
            "SOS" => array("name" => "Somali Shilling", "symbol" => "Sh.so."),
            "ZAR" => array("name" => "South African Rand", "symbol" => "R"),
            "KRW" => array("name" => "South Korean Won", "symbol" => "₩"),
            "SSP" => array("name" => "South Sudanese Pound", "symbol" => "£"),
            "XDR" => array("name" => "Special Drawing Rights", "symbol" => "SDR"),
            "LKR" => array("name" => "Sri Lankan Rupee", "symbol" => "Rs"),
            "SHP" => array("name" => "St. Helena Pound", "symbol" => "£"),
            "SDG" => array("name" => "Sudanese Pound", "symbol" => ".س.ج"),
            "SRD" => array("name" => "Surinamese Dollar", "symbol" => "$"),
            "SZL" => array("name" => "Swazi Lilangeni", "symbol" => "E"),
            "SEK" => array("name" => "Swedish Krona", "symbol" => "kr"),
            "CHF" => array("name" => "Swiss Franc", "symbol" => "CHf"),
            "SYP" => array("name" => "Syrian Pound", "symbol" => "LS"),
            "TJS" => array("name" => "Tajikistani Somoni", "symbol" => "SM"),
            "TZS" => array("name" => "Tanzanian Shilling", "symbol" => "TSh"),
            "THB" => array("name" => "Thai Baht", "symbol" => "฿"),
            "TOP" => array("name" => "Tongan Pa'anga", "symbol" => "$"),
            "TTD" => array("name" => "Trinidad & Tobago Dollar", "symbol" => "$"),
            "TND" => array("name" => "Tunisian Dinar", "symbol" => "ت.د"),
            "TRY" => array("name" => "Turkish Lira", "symbol" => "₺"),
            "TMT" => array("name" => "Turkmenistani Manat", "symbol" => "T"),
            "UGX" => array("name" => "Ugandan Shilling", "symbol" => "USh"),
            "UAH" => array("name" => "Ukrainian Hryvnia", "symbol" => "₴"),
            "AED" => array("name" => "United Arab Emirates Dirham", "symbol" => "إ.د"),
            "UYU" => array("name" => "Uruguayan Peso", "symbol" => "$"),
            "USD" => array("name" => "US Dollar", "symbol" => "$"),
            "UZS" => array("name" => "Uzbekistan Som", "symbol" => "лв"),
            "VUV" => array("name" => "Vanuatu Vatu", "symbol" => "VT"),
            "VEF" => array("name" => "Venezuelan BolÃvar", "symbol" => "Bs"),
            "VND" => array("name" => "Vietnamese Dong", "symbol" => "₫"),
            "YER" => array("name" => "Yemeni Rial", "symbol" => "﷼"),
            "ZMK" => array("name" => "Zambian Kwacha", "symbol" => "ZK"),
            "ZWL" => array("name" => "Zimbabwean dollar", "symbol" => "$")
        ],

    'time_zone' => [
        'Pacific/Midway' => '(UTC-11:00) Midway',
        'Pacific/Niue' => '(UTC-11:00) Niue',
        'Pacific/Pago_Pago' => '(UTC-11:00) Pago Pago',
        'America/Adak' => '(UTC-10:00) Adak',
        'Pacific/Honolulu' => '(UTC-10:00) Honolulu',
        'Pacific/Johnston' => '(UTC-10:00) Johnston',
        'Pacific/Rarotonga' => '(UTC-10:00) Rarotonga',
        'Pacific/Tahiti' => '(UTC-10:00) Tahiti',
        'Pacific/Marquesas' => '(UTC-09:30) Marquesas',
        'America/Anchorage' => '(UTC-09:00) Anchorage',
        'Pacific/Gambier' => '(UTC-09:00) Gambier',
        'America/Juneau' => '(UTC-09:00) Juneau',
        'America/Nome' => '(UTC-09:00) Nome',
        'America/Sitka' => '(UTC-09:00) Sitka',
        'America/Yakutat' => '(UTC-09:00) Yakutat',
        'America/Dawson' => '(UTC-08:00) Dawson',
        'America/Los_Angeles' => '(UTC-08:00) Los Angeles',
        'America/Metlakatla' => '(UTC-08:00) Metlakatla',
        'Pacific/Pitcairn' => '(UTC-08:00) Pitcairn',
        'America/Santa_Isabel' => '(UTC-08:00) Santa Isabel',
        'America/Tijuana' => '(UTC-08:00) Tijuana',
        'America/Vancouver' => '(UTC-08:00) Vancouver',
        'America/Whitehorse' => '(UTC-08:00) Whitehorse',
        'America/Boise' => '(UTC-07:00) Boise',
        'America/Cambridge_Bay' => '(UTC-07:00) Cambridge Bay',
        'America/Chihuahua' => '(UTC-07:00) Chihuahua',
        'America/Creston' => '(UTC-07:00) Creston',
        'America/Dawson_Creek' => '(UTC-07:00) Dawson Creek',
        'America/Denver' => '(UTC-07:00) Denver',
        'America/Edmonton' => '(UTC-07:00) Edmonton',
        'America/Hermosillo' => '(UTC-07:00) Hermosillo',
        'America/Inuvik' => '(UTC-07:00) Inuvik',
        'America/Mazatlan' => '(UTC-07:00) Mazatlan',
        'America/Ojinaga' => '(UTC-07:00) Ojinaga',
        'America/Phoenix' => '(UTC-07:00) Phoenix',
        'America/Shiprock' => '(UTC-07:00) Shiprock',
        'America/Yellowknife' => '(UTC-07:00) Yellowknife',
        'America/Bahia_Banderas' => '(UTC-06:00) Bahia Banderas',
        'America/Belize' => '(UTC-06:00) Belize',
        'America/North_Dakota/Beulah' => '(UTC-06:00) Beulah',
        'America/Cancun' => '(UTC-06:00) Cancun',
        'America/North_Dakota/Center' => '(UTC-06:00) Center',
        'America/Chicago' => '(UTC-06:00) Chicago',
        'America/Costa_Rica' => '(UTC-06:00) Costa Rica',
        'Pacific/Easter' => '(UTC-06:00) Easter',
        'America/El_Salvador' => '(UTC-06:00) El Salvador',
        'Pacific/Galapagos' => '(UTC-06:00) Galapagos',
        'America/Guatemala' => '(UTC-06:00) Guatemala',
        'America/Indiana/Knox' => '(UTC-06:00) Knox',
        'America/Managua' => '(UTC-06:00) Managua',
        'America/Matamoros' => '(UTC-06:00) Matamoros',
        'America/Menominee' => '(UTC-06:00) Menominee',
        'America/Merida' => '(UTC-06:00) Merida',
        'America/Mexico_City' => '(UTC-06:00) Mexico City',
        'America/Monterrey' => '(UTC-06:00) Monterrey',
        'America/North_Dakota/New_Salem' => '(UTC-06:00) New Salem',
        'America/Rainy_River' => '(UTC-06:00) Rainy River',
        'America/Rankin_Inlet' => '(UTC-06:00) Rankin Inlet',
        'America/Regina' => '(UTC-06:00) Regina',
        'America/Resolute' => '(UTC-06:00) Resolute',
        'America/Swift_Current' => '(UTC-06:00) Swift Current',
        'America/Tegucigalpa' => '(UTC-06:00) Tegucigalpa',
        'America/Indiana/Tell_City' => '(UTC-06:00) Tell City',
        'America/Winnipeg' => '(UTC-06:00) Winnipeg',
        'America/Atikokan' => '(UTC-05:00) Atikokan',
        'America/Bogota' => '(UTC-05:00) Bogota',
        'America/Cayman' => '(UTC-05:00) Cayman',
        'America/Detroit' => '(UTC-05:00) Detroit',
        'America/Grand_Turk' => '(UTC-05:00) Grand Turk',
        'America/Guayaquil' => '(UTC-05:00) Guayaquil',
        'America/Havana' => '(UTC-05:00) Havana',
        'America/Indiana/Indianapolis' => '(UTC-05:00) Indianapolis',
        'America/Iqaluit' => '(UTC-05:00) Iqaluit',
        'America/Jamaica' => '(UTC-05:00) Jamaica',
        'America/Lima' => '(UTC-05:00) Lima',
        'America/Kentucky/Louisville' => '(UTC-05:00) Louisville',
        'America/Indiana/Marengo' => '(UTC-05:00) Marengo',
        'America/Kentucky/Monticello' => '(UTC-05:00) Monticello',
        'America/Montreal' => '(UTC-05:00) Montreal',
        'America/Nassau' => '(UTC-05:00) Nassau',
        'America/New_York' => '(UTC-05:00) New York',
        'America/Nipigon' => '(UTC-05:00) Nipigon',
        'America/Panama' => '(UTC-05:00) Panama',
        'America/Pangnirtung' => '(UTC-05:00) Pangnirtung',
        'America/Indiana/Petersburg' => '(UTC-05:00) Petersburg',
        'America/Port-au-Prince' => '(UTC-05:00) Port-au-Prince',
        'America/Thunder_Bay' => '(UTC-05:00) Thunder Bay',
        'America/Toronto' => '(UTC-05:00) Toronto',
        'America/Indiana/Vevay' => '(UTC-05:00) Vevay',
        'America/Indiana/Vincennes' => '(UTC-05:00) Vincennes',
        'America/Indiana/Winamac' => '(UTC-05:00) Winamac',
        'America/Caracas' => '(UTC-04:30) Caracas',
        'America/Anguilla' => '(UTC-04:00) Anguilla',
        'America/Antigua' => '(UTC-04:00) Antigua',
        'America/Aruba' => '(UTC-04:00) Aruba',
        'America/Asuncion' => '(UTC-04:00) Asuncion',
        'America/Barbados' => '(UTC-04:00) Barbados',
        'Atlantic/Bermuda' => '(UTC-04:00) Bermuda',
        'America/Blanc-Sablon' => '(UTC-04:00) Blanc-Sablon',
        'America/Boa_Vista' => '(UTC-04:00) Boa Vista',
        'America/Campo_Grande' => '(UTC-04:00) Campo Grande',
        'America/Cuiaba' => '(UTC-04:00) Cuiaba',
        'America/Curacao' => '(UTC-04:00) Curacao',
        'America/Dominica' => '(UTC-04:00) Dominica',
        'America/Eirunepe' => '(UTC-04:00) Eirunepe',
        'America/Glace_Bay' => '(UTC-04:00) Glace Bay',
        'America/Goose_Bay' => '(UTC-04:00) Goose Bay',
        'America/Grenada' => '(UTC-04:00) Grenada',
        'America/Guadeloupe' => '(UTC-04:00) Guadeloupe',
        'America/Guyana' => '(UTC-04:00) Guyana',
        'America/Halifax' => '(UTC-04:00) Halifax',
        'America/Kralendijk' => '(UTC-04:00) Kralendijk',
        'America/La_Paz' => '(UTC-04:00) La Paz',
        'America/Lower_Princes' => '(UTC-04:00) Lower Princes',
        'America/Manaus' => '(UTC-04:00) Manaus',
        'America/Marigot' => '(UTC-04:00) Marigot',
        'America/Martinique' => '(UTC-04:00) Martinique',
        'America/Moncton' => '(UTC-04:00) Moncton',
        'America/Montserrat' => '(UTC-04:00) Montserrat',
        'Antarctica/Palmer' => '(UTC-04:00) Palmer',
        'America/Port_of_Spain' => '(UTC-04:00) Port of Spain',
        'America/Porto_Velho' => '(UTC-04:00) Porto Velho',
        'America/Puerto_Rico' => '(UTC-04:00) Puerto Rico',
        'America/Rio_Branco' => '(UTC-04:00) Rio Branco',
        'America/Santiago' => '(UTC-04:00) Santiago',
        'America/Santo_Domingo' => '(UTC-04:00) Santo Domingo',
        'America/St_Barthelemy' => '(UTC-04:00) St. Barthelemy',
        'America/St_Kitts' => '(UTC-04:00) St. Kitts',
        'America/St_Lucia' => '(UTC-04:00) St. Lucia',
        'America/St_Thomas' => '(UTC-04:00) St. Thomas',
        'America/St_Vincent' => '(UTC-04:00) St. Vincent',
        'America/Thule' => '(UTC-04:00) Thule',
        'America/Tortola' => '(UTC-04:00) Tortola',
        'America/St_Johns' => '(UTC-03:30) St. Johns',
        'America/Araguaina' => '(UTC-03:00) Araguaina',
        'America/Bahia' => '(UTC-03:00) Bahia',
        'America/Belem' => '(UTC-03:00) Belem',
        'America/Argentina/Buenos_Aires' => '(UTC-03:00) Buenos Aires',
        'America/Argentina/Catamarca' => '(UTC-03:00) Catamarca',
        'America/Cayenne' => '(UTC-03:00) Cayenne',
        'America/Argentina/Cordoba' => '(UTC-03:00) Cordoba',
        'America/Fortaleza' => '(UTC-03:00) Fortaleza',
        'America/Godthab' => '(UTC-03:00) Godthab',
        'America/Argentina/Jujuy' => '(UTC-03:00) Jujuy',
        'America/Argentina/La_Rioja' => '(UTC-03:00) La Rioja',
        'America/Maceio' => '(UTC-03:00) Maceio',
        'America/Argentina/Mendoza' => '(UTC-03:00) Mendoza',
        'America/Miquelon' => '(UTC-03:00) Miquelon',
        'America/Montevideo' => '(UTC-03:00) Montevideo',
        'America/Paramaribo' => '(UTC-03:00) Paramaribo',
        'America/Recife' => '(UTC-03:00) Recife',
        'America/Argentina/Rio_Gallegos' => '(UTC-03:00) Rio Gallegos',
        'Antarctica/Rothera' => '(UTC-03:00) Rothera',
        'America/Argentina/Salta' => '(UTC-03:00) Salta',
        'America/Argentina/San_Juan' => '(UTC-03:00) San Juan',
        'America/Argentina/San_Luis' => '(UTC-03:00) San Luis',
        'America/Santarem' => '(UTC-03:00) Santarem',
        'America/Sao_Paulo' => '(UTC-03:00) Sao Paulo',
        'Atlantic/Stanley' => '(UTC-03:00) Stanley',
        'America/Argentina/Tucuman' => '(UTC-03:00) Tucuman',
        'America/Argentina/Ushuaia' => '(UTC-03:00) Ushuaia',
        'America/Noronha' => '(UTC-02:00) Noronha',
        'Atlantic/South_Georgia' => '(UTC-02:00) South Georgia',
        'Atlantic/Azores' => '(UTC-01:00) Azores',
        'Atlantic/Cape_Verde' => '(UTC-01:00) Cape Verde',
        'America/Scoresbysund' => '(UTC-01:00) Scoresbysund',
        'Africa/Abidjan' => '(UTC+00:00) Abidjan',
        'Africa/Accra' => '(UTC+00:00) Accra',
        'Africa/Bamako' => '(UTC+00:00) Bamako',
        'Africa/Banjul' => '(UTC+00:00) Banjul',
        'Africa/Bissau' => '(UTC+00:00) Bissau',
        'Atlantic/Canary' => '(UTC+00:00) Canary',
        'Africa/Casablanca' => '(UTC+00:00) Casablanca',
        'Africa/Conakry' => '(UTC+00:00) Conakry',
        'Africa/Dakar' => '(UTC+00:00) Dakar',
        'America/Danmarkshavn' => '(UTC+00:00) Danmarkshavn',
        'Europe/Dublin' => '(UTC+00:00) Dublin',
        'Africa/El_Aaiun' => '(UTC+00:00) El Aaiun',
        'Atlantic/Faroe' => '(UTC+00:00) Faroe',
        'Africa/Freetown' => '(UTC+00:00) Freetown',
        'Europe/Guernsey' => '(UTC+00:00) Guernsey',
        'Europe/Isle_of_Man' => '(UTC+00:00) Isle of Man',
        'Europe/Jersey' => '(UTC+00:00) Jersey',
        'Europe/Lisbon' => '(UTC+00:00) Lisbon',
        'Africa/Lome' => '(UTC+00:00) Lome',
        'Europe/London' => '(UTC+00:00) London',
        'Atlantic/Madeira' => '(UTC+00:00) Madeira',
        'Africa/Monrovia' => '(UTC+00:00) Monrovia',
        'Africa/Nouakchott' => '(UTC+00:00) Nouakchott',
        'Africa/Ouagadougou' => '(UTC+00:00) Ouagadougou',
        'Atlantic/Reykjavik' => '(UTC+00:00) Reykjavik',
        'Africa/Sao_Tome' => '(UTC+00:00) Sao Tome',
        'Atlantic/St_Helena' => '(UTC+00:00) St. Helena',
        'UTC' => '(UTC+00:00) UTC',
        'Africa/Algiers' => '(UTC+01:00) Algiers',
        'Europe/Amsterdam' => '(UTC+01:00) Amsterdam',
        'Europe/Andorra' => '(UTC+01:00) Andorra',
        'Africa/Bangui' => '(UTC+01:00) Bangui',
        'Europe/Belgrade' => '(UTC+01:00) Belgrade',
        'Europe/Berlin' => '(UTC+01:00) Berlin',
        'Europe/Bratislava' => '(UTC+01:00) Bratislava',
        'Africa/Brazzaville' => '(UTC+01:00) Brazzaville',
        'Europe/Brussels' => '(UTC+01:00) Brussels',
        'Europe/Budapest' => '(UTC+01:00) Budapest',
        'Europe/Busingen' => '(UTC+01:00) Busingen',
        'Africa/Ceuta' => '(UTC+01:00) Ceuta',
        'Europe/Copenhagen' => '(UTC+01:00) Copenhagen',
        'Africa/Douala' => '(UTC+01:00) Douala',
        'Europe/Gibraltar' => '(UTC+01:00) Gibraltar',
        'Africa/Kinshasa' => '(UTC+01:00) Kinshasa',
        'Africa/Lagos' => '(UTC+01:00) Lagos',
        'Africa/Libreville' => '(UTC+01:00) Libreville',
        'Europe/Ljubljana' => '(UTC+01:00) Ljubljana',
        'Arctic/Longyearbyen' => '(UTC+01:00) Longyearbyen',
        'Africa/Luanda' => '(UTC+01:00) Luanda',
        'Europe/Luxembourg' => '(UTC+01:00) Luxembourg',
        'Europe/Madrid' => '(UTC+01:00) Madrid',
        'Africa/Malabo' => '(UTC+01:00) Malabo',
        'Europe/Malta' => '(UTC+01:00) Malta',
        'Europe/Monaco' => '(UTC+01:00) Monaco',
        'Africa/Ndjamena' => '(UTC+01:00) Ndjamena',
        'Africa/Niamey' => '(UTC+01:00) Niamey',
        'Europe/Oslo' => '(UTC+01:00) Oslo',
        'Europe/Paris' => '(UTC+01:00) Paris',
        'Europe/Podgorica' => '(UTC+01:00) Podgorica',
        'Africa/Porto-Novo' => '(UTC+01:00) Porto-Novo',
        'Europe/Prague' => '(UTC+01:00) Prague',
        'Europe/Rome' => '(UTC+01:00) Rome',
        'Europe/San_Marino' => '(UTC+01:00) San Marino',
        'Europe/Sarajevo' => '(UTC+01:00) Sarajevo',
        'Europe/Skopje' => '(UTC+01:00) Skopje',
        'Europe/Stockholm' => '(UTC+01:00) Stockholm',
        'Europe/Tirane' => '(UTC+01:00) Tirane',
        'Africa/Tripoli' => '(UTC+01:00) Tripoli',
        'Africa/Tunis' => '(UTC+01:00) Tunis',
        'Europe/Vaduz' => '(UTC+01:00) Vaduz',
        'Europe/Vatican' => '(UTC+01:00) Vatican',
        'Europe/Vienna' => '(UTC+01:00) Vienna',
        'Europe/Warsaw' => '(UTC+01:00) Warsaw',
        'Africa/Windhoek' => '(UTC+01:00) Windhoek',
        'Europe/Zagreb' => '(UTC+01:00) Zagreb',
        'Europe/Zurich' => '(UTC+01:00) Zurich',
        'Europe/Athens' => '(UTC+02:00) Athens',
        'Asia/Beirut' => '(UTC+02:00) Beirut',
        'Africa/Blantyre' => '(UTC+02:00) Blantyre',
        'Europe/Bucharest' => '(UTC+02:00) Bucharest',
        'Africa/Bujumbura' => '(UTC+02:00) Bujumbura',
        'Africa/Cairo' => '(UTC+02:00) Cairo',
        'Europe/Chisinau' => '(UTC+02:00) Chisinau',
        'Asia/Damascus' => '(UTC+02:00) Damascus',
        'Africa/Gaborone' => '(UTC+02:00) Gaborone',
        'Asia/Gaza' => '(UTC+02:00) Gaza',
        'Africa/Harare' => '(UTC+02:00) Harare',
        'Asia/Hebron' => '(UTC+02:00) Hebron',
        'Europe/Helsinki' => '(UTC+02:00) Helsinki',
        'Europe/Istanbul' => '(UTC+02:00) Istanbul',
        'Asia/Jerusalem' => '(UTC+02:00) Jerusalem',
        'Africa/Johannesburg' => '(UTC+02:00) Johannesburg',
        'Europe/Kiev' => '(UTC+02:00) Kiev',
        'Africa/Kigali' => '(UTC+02:00) Kigali',
        'Africa/Lubumbashi' => '(UTC+02:00) Lubumbashi',
        'Africa/Lusaka' => '(UTC+02:00) Lusaka',
        'Africa/Maputo' => '(UTC+02:00) Maputo',
        'Europe/Mariehamn' => '(UTC+02:00) Mariehamn',
        'Africa/Maseru' => '(UTC+02:00) Maseru',
        'Africa/Mbabane' => '(UTC+02:00) Mbabane',
        'Asia/Nicosia' => '(UTC+02:00) Nicosia',
        'Europe/Riga' => '(UTC+02:00) Riga',
        'Europe/Simferopol' => '(UTC+02:00) Simferopol',
        'Europe/Sofia' => '(UTC+02:00) Sofia',
        'Europe/Tallinn' => '(UTC+02:00) Tallinn',
        'Europe/Uzhgorod' => '(UTC+02:00) Uzhgorod',
        'Europe/Vilnius' => '(UTC+02:00) Vilnius',
        'Europe/Zaporozhye' => '(UTC+02:00) Zaporozhye',
        'Africa/Addis_Ababa' => '(UTC+03:00) Addis Ababa',
        'Asia/Aden' => '(UTC+03:00) Aden',
        'Asia/Amman' => '(UTC+03:00) Amman',
        'Indian/Antananarivo' => '(UTC+03:00) Antananarivo',
        'Africa/Asmara' => '(UTC+03:00) Asmara',
        'Asia/Baghdad' => '(UTC+03:00) Baghdad',
        'Asia/Bahrain' => '(UTC+03:00) Bahrain',
        'Indian/Comoro' => '(UTC+03:00) Comoro',
        'Africa/Dar_es_Salaam' => '(UTC+03:00) Dar es Salaam',
        'Africa/Djibouti' => '(UTC+03:00) Djibouti',
        'Africa/Juba' => '(UTC+03:00) Juba',
        'Europe/Kaliningrad' => '(UTC+03:00) Kaliningrad',
        'Africa/Kampala' => '(UTC+03:00) Kampala',
        'Africa/Khartoum' => '(UTC+03:00) Khartoum',
        'Asia/Kuwait' => '(UTC+03:00) Kuwait',
        'Indian/Mayotte' => '(UTC+03:00) Mayotte',
        'Europe/Minsk' => '(UTC+03:00) Minsk',
        'Africa/Mogadishu' => '(UTC+03:00) Mogadishu',
        'Europe/Moscow' => '(UTC+03:00) Moscow',
        'Africa/Nairobi' => '(UTC+03:00) Nairobi',
        'Asia/Qatar' => '(UTC+03:00) Qatar',
        'Asia/Riyadh' => '(UTC+03:00) Riyadh',
        'Antarctica/Syowa' => '(UTC+03:00) Syowa',
        'Asia/Tehran' => '(UTC+03:30) Tehran',
        'Asia/Baku' => '(UTC+04:00) Baku',
        'Asia/Dubai' => '(UTC+04:00) Dubai',
        'Indian/Mahe' => '(UTC+04:00) Mahe',
        'Indian/Mauritius' => '(UTC+04:00) Mauritius',
        'Asia/Muscat' => '(UTC+04:00) Muscat',
        'Indian/Reunion' => '(UTC+04:00) Reunion',
        'Europe/Samara' => '(UTC+04:00) Samara',
        'Asia/Tbilisi' => '(UTC+04:00) Tbilisi',
        'Europe/Volgograd' => '(UTC+04:00) Volgograd',
        'Asia/Yerevan' => '(UTC+04:00) Yerevan',
        'Asia/Kabul' => '(UTC+04:30) Kabul',
        'Asia/Aqtau' => '(UTC+05:00) Aqtau',
        'Asia/Aqtobe' => '(UTC+05:00) Aqtobe',
        'Asia/Ashgabat' => '(UTC+05:00) Ashgabat',
        'Asia/Dushanbe' => '(UTC+05:00) Dushanbe',
        'Asia/Karachi' => '(UTC+05:00) Karachi',
        'Indian/Kerguelen' => '(UTC+05:00) Kerguelen',
        'Indian/Maldives' => '(UTC+05:00) Maldives',
        'Antarctica/Mawson' => '(UTC+05:00) Mawson',
        'Asia/Oral' => '(UTC+05:00) Oral',
        'Asia/Samarkand' => '(UTC+05:00) Samarkand',
        'Asia/Tashkent' => '(UTC+05:00) Tashkent',
        'Asia/Colombo' => '(UTC+05:30) Colombo',
        'Asia/Kolkata' => '(UTC+05:30) Kolkata',
        'Asia/Kathmandu' => '(UTC+05:45) Kathmandu',
        'Asia/Almaty' => '(UTC+06:00) Almaty',
        'Asia/Bishkek' => '(UTC+06:00) Bishkek',
        'Indian/Chagos' => '(UTC+06:00) Chagos',
        'Asia/Dhaka' => '(UTC+06:00) Dhaka',
        'Asia/Qyzylorda' => '(UTC+06:00) Qyzylorda',
        'Asia/Thimphu' => '(UTC+06:00) Thimphu',
        'Antarctica/Vostok' => '(UTC+06:00) Vostok',
        'Asia/Yekaterinburg' => '(UTC+06:00) Yekaterinburg',
        'Indian/Cocos' => '(UTC+06:30) Cocos',
        'Asia/Rangoon' => '(UTC+06:30) Rangoon',
        'Asia/Bangkok' => '(UTC+07:00) Bangkok',
        'Indian/Christmas' => '(UTC+07:00) Christmas',
        'Antarctica/Davis' => '(UTC+07:00) Davis',
        'Asia/Ho_Chi_Minh' => '(UTC+07:00) Ho Chi Minh',
        'Asia/Hovd' => '(UTC+07:00) Hovd',
        'Asia/Jakarta' => '(UTC+07:00) Jakarta',
        'Asia/Novokuznetsk' => '(UTC+07:00) Novokuznetsk',
        'Asia/Novosibirsk' => '(UTC+07:00) Novosibirsk',
        'Asia/Omsk' => '(UTC+07:00) Omsk',
        'Asia/Phnom_Penh' => '(UTC+07:00) Phnom Penh',
        'Asia/Pontianak' => '(UTC+07:00) Pontianak',
        'Asia/Vientiane' => '(UTC+07:00) Vientiane',
        'Asia/Brunei' => '(UTC+08:00) Brunei',
        'Antarctica/Casey' => '(UTC+08:00) Casey',
        'Asia/Choibalsan' => '(UTC+08:00) Choibalsan',
        'Asia/Chongqing' => '(UTC+08:00) Chongqing',
        'Asia/Harbin' => '(UTC+08:00) Harbin',
        'Asia/Hong_Kong' => '(UTC+08:00) Hong Kong',
        'Asia/Kashgar' => '(UTC+08:00) Kashgar',
        'Asia/Krasnoyarsk' => '(UTC+08:00) Krasnoyarsk',
        'Asia/Kuala_Lumpur' => '(UTC+08:00) Kuala Lumpur',
        'Asia/Kuching' => '(UTC+08:00) Kuching',
        'Asia/Macau' => '(UTC+08:00) Macau',
        'Asia/Makassar' => '(UTC+08:00) Makassar',
        'Asia/Manila' => '(UTC+08:00) Manila',
        'Australia/Perth' => '(UTC+08:00) Perth',
        'Asia/Shanghai' => '(UTC+08:00) Shanghai',
        'Asia/Singapore' => '(UTC+08:00) Singapore',
        'Asia/Taipei' => '(UTC+08:00) Taipei',
        'Asia/Ulaanbaatar' => '(UTC+08:00) Ulaanbaatar',
        'Asia/Urumqi' => '(UTC+08:00) Urumqi',
        'Australia/Eucla' => '(UTC+08:45) Eucla',
        'Asia/Dili' => '(UTC+09:00) Dili',
        'Asia/Irkutsk' => '(UTC+09:00) Irkutsk',
        'Asia/Jayapura' => '(UTC+09:00) Jayapura',
        'Pacific/Palau' => '(UTC+09:00) Palau',
        'Asia/Pyongyang' => '(UTC+09:00) Pyongyang',
        'Asia/Seoul' => '(UTC+09:00) Seoul',
        'Asia/Tokyo' => '(UTC+09:00) Tokyo',
        'Australia/Adelaide' => '(UTC+09:30) Adelaide',
        'Australia/Broken_Hill' => '(UTC+09:30) Broken Hill',
        'Australia/Darwin' => '(UTC+09:30) Darwin',
        'Australia/Brisbane' => '(UTC+10:00) Brisbane',
        'Pacific/Chuuk' => '(UTC+10:00) Chuuk',
        'Australia/Currie' => '(UTC+10:00) Currie',
        'Antarctica/DumontDUrville' => '(UTC+10:00) DumontDUrville',
        'Pacific/Guam' => '(UTC+10:00) Guam',
        'Australia/Hobart' => '(UTC+10:00) Hobart',
        'Asia/Khandyga' => '(UTC+10:00) Khandyga',
        'Australia/Lindeman' => '(UTC+10:00) Lindeman',
        'Australia/Melbourne' => '(UTC+10:00) Melbourne',
        'Pacific/Port_Moresby' => '(UTC+10:00) Port Moresby',
        'Pacific/Saipan' => '(UTC+10:00) Saipan',
        'Australia/Sydney' => '(UTC+10:00) Sydney',
        'Asia/Yakutsk' => '(UTC+10:00) Yakutsk',
        'Australia/Lord_Howe' => '(UTC+10:30) Lord Howe',
        'Pacific/Efate' => '(UTC+11:00) Efate',
        'Pacific/Guadalcanal' => '(UTC+11:00) Guadalcanal',
        'Pacific/Kosrae' => '(UTC+11:00) Kosrae',
        'Antarctica/Macquarie' => '(UTC+11:00) Macquarie',
        'Pacific/Noumea' => '(UTC+11:00) Noumea',
        'Pacific/Pohnpei' => '(UTC+11:00) Pohnpei',
        'Asia/Sakhalin' => '(UTC+11:00) Sakhalin',
        'Asia/Ust-Nera' => '(UTC+11:00) Ust-Nera',
        'Asia/Vladivostok' => '(UTC+11:00) Vladivostok',
        'Pacific/Norfolk' => '(UTC+11:30) Norfolk',
        'Asia/Anadyr' => '(UTC+12:00) Anadyr',
        'Pacific/Auckland' => '(UTC+12:00) Auckland',
        'Pacific/Fiji' => '(UTC+12:00) Fiji',
        'Pacific/Funafuti' => '(UTC+12:00) Funafuti',
        'Asia/Kamchatka' => '(UTC+12:00) Kamchatka',
        'Pacific/Kwajalein' => '(UTC+12:00) Kwajalein',
        'Asia/Magadan' => '(UTC+12:00) Magadan',
        'Pacific/Majuro' => '(UTC+12:00) Majuro',
        'Antarctica/McMurdo' => '(UTC+12:00) McMurdo',
        'Pacific/Nauru' => '(UTC+12:00) Nauru',
        'Antarctica/South_Pole' => '(UTC+12:00) South Pole',
        'Pacific/Tarawa' => '(UTC+12:00) Tarawa',
        'Pacific/Wake' => '(UTC+12:00) Wake',
        'Pacific/Wallis' => '(UTC+12:00) Wallis',
        'Pacific/Chatham' => '(UTC+12:45) Chatham',
        'Pacific/Apia' => '(UTC+13:00) Apia',
        'Pacific/Enderbury' => '(UTC+13:00) Enderbury',
        'Pacific/Fakaofo' => '(UTC+13:00) Fakaofo',
        'Pacific/Tongatapu' => '(UTC+13:00) Tongatapu',
        'Pacific/Kiritimati' => '(UTC+14:00) Kiritimati',
    ],

    'country_list' => [
        "AF" => array("name" => "Afghanistan", "capital" => "Kabul"),
        "AX" => array("name" => "Aland Islands", "capital" => "Mariehamn"),
        "AL" => array("name" => "Albania", "capital" => "Tirana"),
        "DZ" => array("name" => "Algeria", "capital" => "Algiers"),
        "AS" => array("name" => "American Samoa", "capital" => "Pago Pago"),
        "AD" => array("name" => "Andorra", "capital" => "Andorra la Vella"),
        "AO" => array("name" => "Angola", "capital" => "Luanda"),
        "AI" => array("name" => "Anguilla", "capital" => "The Valley"),
        "AQ" => array("name" => "Antarctica", "capital" => "Antarctica"),
        "AG" => array("name" => "Antigua and Barbuda", "capital" => "St. John's"),
        "AR" => array("name" => "Argentina", "capital" => "Buenos Aires"),
        "AM" => array("name" => "Armenia", "capital" => "Yerevan"),
        "AW" => array("name" => "Aruba", "capital" => "Oranjestad"),
        "AU" => array("name" => "Australia", "capital" => "Canberra"),
        "AT" => array("name" => "Austria", "capital" => "Vienna"),
        "AZ" => array("name" => "Azerbaijan", "capital" => "Baku"),
        "BS" => array("name" => "Bahamas", "capital" => "Nassau"),
        "BH" => array("name" => "Bahrain", "capital" => "Manama"),
        "BD" => array("name" => "Bangladesh", "capital" => "Dhaka"),
        "BB" => array("name" => "Barbados", "capital" => "Bridgetown"),
        "BY" => array("name" => "Belarus", "capital" => "Minsk"),
        "BE" => array("name" => "Belgium", "capital" => "Brussels"),
        "BZ" => array("name" => "Belize", "capital" => "Belmopan"),
        "BJ" => array("name" => "Benin", "capital" => "Porto-Novo"),
        "BM" => array("name" => "Bermuda", "capital" => "Hamilton"),
        "BT" => array("name" => "Bhutan", "capital" => "Thimphu"),
        "BO" => array("name" => "Bolivia", "capital" => "Sucre"),
        "BQ" => array("name" => "Bonaire, Sint Eustatius and Saba", "capital" => "Kralendijk"),
        "BA" => array("name" => "Bosnia and Herzegovina", "capital" => "Sarajevo"),
        "BW" => array("name" => "Botswana", "capital" => "Gaborone"),
        "BV" => array("name" => "Bouvet Island", "capital" => ""),
        "BR" => array("name" => "Brazil", "capital" => "Brasilia"),
        "IO" => array("name" => "British Indian Ocean Territory", "capital" => "Diego Garcia"),
        "BN" => array("name" => "Brunei Darussalam", "capital" => "Bandar Seri Begawan"),
        "BG" => array("name" => "Bulgaria", "capital" => "Sofia"),
        "BF" => array("name" => "Burkina Faso", "capital" => "Ouagadougou"),
        "BI" => array("name" => "Burundi", "capital" => "Bujumbura"),
        "KH" => array("name" => "Cambodia", "capital" => "Phnom Penh"),
        "CM" => array("name" => "Cameroon", "capital" => "Yaounde"),
        "CA" => array("name" => "Canada", "capital" => "Ottawa"),
        "CV" => array("name" => "Cape Verde", "capital" => "Praia"),
        "KY" => array("name" => "Cayman Islands", "capital" => "George Town"),
        "CF" => array("name" => "Central African Republic", "capital" => "Bangui"),
        "TD" => array("name" => "Chad", "capital" => "N'Djamena"),
        "CL" => array("name" => "Chile", "capital" => "Santiago"),
        "CN" => array("name" => "China", "capital" => "Beijing"),
        "CX" => array("name" => "Christmas Island", "capital" => "Flying Fish Cove"),
        "CC" => array("name" => "Cocos (Keeling) Islands", "capital" => "West Island"),
        "CO" => array("name" => "Colombia", "capital" => "Bogota"),
        "KM" => array("name" => "Comoros", "capital" => "Moroni"),
        "CG" => array("name" => "Congo", "capital" => "Brazzaville"),
        "CD" => array("name" => "Congo, Democratic Republic of the Congo", "capital" => "Kinshasa"),
        "CK" => array("name" => "Cook Islands", "capital" => "Avarua"),
        "CR" => array("name" => "Costa Rica", "capital" => "San Jose"),
        "CI" => array("name" => "Cote D'Ivoire", "capital" => "Yamoussoukro"),
        "HR" => array("name" => "Croatia", "capital" => "Zagreb"),
        "CU" => array("name" => "Cuba", "capital" => "Havana"),
        "CW" => array("name" => "Curacao", "capital" => "Willemstad"),
        "CY" => array("name" => "Cyprus", "capital" => "Nicosia"),
        "CZ" => array("name" => "Czech Republic", "capital" => "Prague"),
        "DK" => array("name" => "Denmark", "capital" => "Copenhagen"),
        "DJ" => array("name" => "Djibouti", "capital" => "Djibouti"),
        "DM" => array("name" => "Dominica", "capital" => "Roseau"),
        "DO" => array("name" => "Dominican Republic", "capital" => "Santo Domingo"),
        "EC" => array("name" => "Ecuador", "capital" => "Quito"),
        "EG" => array("name" => "Egypt", "capital" => "Cairo"),
        "SV" => array("name" => "El Salvador", "capital" => "San Salvador"),
        "GQ" => array("name" => "Equatorial Guinea", "capital" => "Malabo"),
        "ER" => array("name" => "Eritrea", "capital" => "Asmara"),
        "EE" => array("name" => "Estonia", "capital" => "Tallinn"),
        "ET" => array("name" => "Ethiopia", "capital" => "Addis Ababa"),
        "FK" => array("name" => "Falkland Islands (Malvinas)", "capital" => "Stanley"),
        "FO" => array("name" => "Faroe Islands", "capital" => "Torshavn"),
        "FJ" => array("name" => "Fiji", "capital" => "Suva"),
        "FI" => array("name" => "Finland", "capital" => "Helsinki"),
        "FR" => array("name" => "France", "capital" => "Paris"),
        "GF" => array("name" => "French Guiana", "capital" => "Cayenne"),
        "PF" => array("name" => "French Polynesia", "capital" => "Papeete"),
        "TF" => array("name" => "French Southern Territories", "capital" => "Port-aux-Francais"),
        "GA" => array("name" => "Gabon", "capital" => "Libreville"),
        "GM" => array("name" => "Gambia", "capital" => "Banjul"),
        "GE" => array("name" => "Georgia", "capital" => "Tbilisi"),
        "DE" => array("name" => "Germany", "capital" => "Berlin"),
        "GH" => array("name" => "Ghana", "capital" => "Accra"),
        "GI" => array("name" => "Gibraltar", "capital" => "Gibraltar"),
        "GR" => array("name" => "Greece", "capital" => "Athens"),
        "GL" => array("name" => "Greenland", "capital" => "Nuuk"),
        "GD" => array("name" => "Grenada", "capital" => "St. George's"),
        "GP" => array("name" => "Guadeloupe", "capital" => "Basse-Terre"),
        "GU" => array("name" => "Guam", "capital" => "Hagatna"),
        "GT" => array("name" => "Guatemala", "capital" => "Guatemala City"),
        "GG" => array("name" => "Guernsey", "capital" => "St Peter Port"),
        "GN" => array("name" => "Guinea", "capital" => "Conakry"),
        "GW" => array("name" => "Guinea-Bissau", "capital" => "Bissau"),
        "GY" => array("name" => "Guyana", "capital" => "Georgetown"),
        "HT" => array("name" => "Haiti", "capital" => "Port-au-Prince"),
        "HM" => array("name" => "Heard Island and McDonald Islands", "capital" => ""),
        "VA" => array("name" => "Holy See (Vatican City State)", "capital" => "Vatican City"),
        "HN" => array("name" => "Honduras", "capital" => "Tegucigalpa"),
        "HK" => array("name" => "Hong Kong", "capital" => "Hong Kong"),
        "HU" => array("name" => "Hungary", "capital" => "Budapest"),
        "IS" => array("name" => "Iceland", "capital" => "Reykjavik"),
        "IN" => array("name" => "India", "capital" => "New Delhi"),
        "ID" => array("name" => "Indonesia", "capital" => "Jakarta"),
        "IR" => array("name" => "Iran, Islamic Republic of", "capital" => "Tehran"),
        "IQ" => array("name" => "Iraq", "capital" => "Baghdad"),
        "IE" => array("name" => "Ireland", "capital" => "Dublin"),
        "IM" => array("name" => "Isle of Man", "capital" => "Douglas, Isle of Man"),
        "IL" => array("name" => "Israel", "capital" => "Jerusalem"),
        "IT" => array("name" => "Italy", "capital" => "Rome"),
        "JM" => array("name" => "Jamaica", "capital" => "Kingston"),
        "JP" => array("name" => "Japan", "capital" => "Tokyo"),
        "JE" => array("name" => "Jersey", "capital" => "Saint Helier"),
        "JO" => array("name" => "Jordan", "capital" => "Amman"),
        "KZ" => array("name" => "Kazakhstan", "capital" => "Astana"),
        "KE" => array("name" => "Kenya", "capital" => "Nairobi"),
        "KI" => array("name" => "Kiribati", "capital" => "Tarawa"),
        "KP" => array("name" => "Korea, Democratic People's Republic of", "capital" => "Pyongyang"),
        "KR" => array("name" => "Korea, Republic of", "capital" => "Seoul"),
        "XK" => array("name" => "Kosovo", "capital" => "Pristina"),
        "KW" => array("name" => "Kuwait", "capital" => "Kuwait City"),
        "KG" => array("name" => "Kyrgyzstan", "capital" => "Bishkek"),
        "LA" => array("name" => "Lao People's Democratic Republic", "capital" => "Vientiane"),
        "LV" => array("name" => "Latvia", "capital" => "Riga"),
        "LB" => array("name" => "Lebanon", "capital" => "Beirut"),
        "LS" => array("name" => "Lesotho", "capital" => "Maseru"),
        "LR" => array("name" => "Liberia", "capital" => "Monrovia"),
        "LY" => array("name" => "Libyan Arab Jamahiriya", "capital" => "Tripolis"),
        "LI" => array("name" => "Liechtenstein", "capital" => "Vaduz"),
        "LT" => array("name" => "Lithuania", "capital" => "Vilnius"),
        "LU" => array("name" => "Luxembourg", "capital" => "Luxembourg"),
        "MO" => array("name" => "Macao", "capital" => "Macao"),
        "MK" => array("name" => "Macedonia, the Former Yugoslav Republic of", "capital" => "Skopje"),
        "MG" => array("name" => "Madagascar", "capital" => "Antananarivo"),
        "MW" => array("name" => "Malawi", "capital" => "Lilongwe"),
        "MY" => array("name" => "Malaysia", "capital" => "Kuala Lumpur"),
        "MV" => array("name" => "Maldives", "capital" => "Male"),
        "ML" => array("name" => "Mali", "capital" => "Bamako"),
        "MT" => array("name" => "Malta", "capital" => "Valletta"),
        "MH" => array("name" => "Marshall Islands", "capital" => "Majuro"),
        "MQ" => array("name" => "Martinique", "capital" => "Fort-de-France"),
        "MR" => array("name" => "Mauritania", "capital" => "Nouakchott"),
        "MU" => array("name" => "Mauritius", "capital" => "Port Louis"),
        "YT" => array("name" => "Mayotte", "capital" => "Mamoudzou"),
        "MX" => array("name" => "Mexico", "capital" => "Mexico City"),
        "FM" => array("name" => "Micronesia, Federated States of", "capital" => "Palikir"),
        "MD" => array("name" => "Moldova, Republic of", "capital" => "Chisinau"),
        "MC" => array("name" => "Monaco", "capital" => "Monaco"),
        "MN" => array("name" => "Mongolia", "capital" => "Ulan Bator"),
        "ME" => array("name" => "Montenegro", "capital" => "Podgorica"),
        "MS" => array("name" => "Montserrat", "capital" => "Plymouth"),
        "MA" => array("name" => "Morocco", "capital" => "Rabat"),
        "MZ" => array("name" => "Mozambique", "capital" => "Maputo"),
        "MM" => array("name" => "Myanmar", "capital" => "Nay Pyi Taw"),
        "NA" => array("name" => "Namibia", "capital" => "Windhoek"),
        "NR" => array("name" => "Nauru", "capital" => "Yaren"),
        "NP" => array("name" => "Nepal", "capital" => "Kathmandu"),
        "NL" => array("name" => "Netherlands", "capital" => "Amsterdam"),
        "AN" => array("name" => "Netherlands Antilles", "capital" => "Willemstad"),
        "NC" => array("name" => "New Caledonia", "capital" => "Noumea"),
        "NZ" => array("name" => "New Zealand", "capital" => "Wellington"),
        "NI" => array("name" => "Nicaragua", "capital" => "Managua"),
        "NE" => array("name" => "Niger", "capital" => "Niamey"),
        "NG" => array("name" => "Nigeria", "capital" => "Abuja"),
        "NU" => array("name" => "Niue", "capital" => "Alofi"),
        "NF" => array("name" => "Norfolk Island", "capital" => "Kingston"),
        "MP" => array("name" => "Northern Mariana Islands", "capital" => "Saipan"),
        "NO" => array("name" => "Norway", "capital" => "Oslo"),
        "OM" => array("name" => "Oman", "capital" => "Muscat"),
        "PK" => array("name" => "Pakistan", "capital" => "Islamabad"),
        "PW" => array("name" => "Palau", "capital" => "Melekeok"),
        "PS" => array("name" => "Palestinian Territory, Occupied", "capital" => "East Jerusalem"),
        "PA" => array("name" => "Panama", "capital" => "Panama City"),
        "PG" => array("name" => "Papua New Guinea", "capital" => "Port Moresby"),
        "PY" => array("name" => "Paraguay", "capital" => "Asuncion"),
        "PE" => array("name" => "Peru", "capital" => "Lima"),
        "PH" => array("name" => "Philippines", "capital" => "Manila"),
        "PN" => array("name" => "Pitcairn", "capital" => "Adamstown"),
        "PL" => array("name" => "Poland", "capital" => "Warsaw"),
        "PT" => array("name" => "Portugal", "capital" => "Lisbon"),
        "PR" => array("name" => "Puerto Rico", "capital" => "San Juan"),
        "QA" => array("name" => "Qatar", "capital" => "Doha"),
        "RE" => array("name" => "Reunion", "capital" => "Saint-Denis"),
        "RO" => array("name" => "Romania", "capital" => "Bucharest"),
        "RU" => array("name" => "Russian Federation", "capital" => "Moscow"),
        "RW" => array("name" => "Rwanda", "capital" => "Kigali"),
        "BL" => array("name" => "Saint Barthelemy", "capital" => "Gustavia"),
        "SH" => array("name" => "Saint Helena", "capital" => "Jamestown"),
        "KN" => array("name" => "Saint Kitts and Nevis", "capital" => "Basseterre"),
        "LC" => array("name" => "Saint Lucia", "capital" => "Castries"),
        "MF" => array("name" => "Saint Martin", "capital" => "Marigot"),
        "PM" => array("name" => "Saint Pierre and Miquelon", "capital" => "Saint-Pierre"),
        "VC" => array("name" => "Saint Vincent and the Grenadines", "capital" => "Kingstown"),
        "WS" => array("name" => "Samoa", "capital" => "Apia"),
        "SM" => array("name" => "San Marino", "capital" => "San Marino"),
        "ST" => array("name" => "Sao Tome and Principe", "capital" => "Sao Tome"),
        "SA" => array("name" => "Saudi Arabia", "capital" => "Riyadh"),
        "SN" => array("name" => "Senegal", "capital" => "Dakar"),
        "RS" => array("name" => "Serbia", "capital" => "Belgrade"),
        "CS" => array("name" => "Serbia and Montenegro", "capital" => "Belgrade"),
        "SC" => array("name" => "Seychelles", "capital" => "Victoria"),
        "SL" => array("name" => "Sierra Leone", "capital" => "Freetown"),
        "SG" => array("name" => "Singapore", "capital" => "Singapur"),
        "SX" => array("name" => "St Martin", "capital" => "Philipsburg"),
        "SK" => array("name" => "Slovakia", "capital" => "Bratislava"),
        "SI" => array("name" => "Slovenia", "capital" => "Ljubljana"),
        "SB" => array("name" => "Solomon Islands", "capital" => "Honiara"),
        "SO" => array("name" => "Somalia", "capital" => "Mogadishu"),
        "ZA" => array("name" => "South Africa", "capital" => "Pretoria"),
        "GS" => array("name" => "South Georgia and the South Sandwich Islands", "capital" => "Grytviken"),
        "SS" => array("name" => "South Sudan", "capital" => "Juba"),
        "ES" => array("name" => "Spain", "capital" => "Madrid"),
        "LK" => array("name" => "Sri Lanka", "capital" => "Colombo"),
        "SD" => array("name" => "Sudan", "capital" => "Khartoum"),
        "SR" => array("name" => "Suriname", "capital" => "Paramaribo"),
        "SJ" => array("name" => "Svalbard and Jan Mayen", "capital" => "Longyearbyen"),
        "SZ" => array("name" => "Swaziland", "capital" => "Mbabane"),
        "SE" => array("name" => "Sweden", "capital" => "Stockholm"),
        "CH" => array("name" => "Switzerland", "capital" => "Berne"),
        "SY" => array("name" => "Syrian Arab Republic", "capital" => "Damascus"),
        "TW" => array("name" => "Taiwan, Province of China", "capital" => "Taipei"),
        "TJ" => array("name" => "Tajikistan", "capital" => "Dushanbe"),
        "TZ" => array("name" => "Tanzania, United Republic of", "capital" => "Dodoma"),
        "TH" => array("name" => "Thailand", "capital" => "Bangkok"),
        "TL" => array("name" => "Timor-Leste", "capital" => "Dili"),
        "TG" => array("name" => "Togo", "capital" => "Lome"),
        "TK" => array("name" => "Tokelau", "capital" => ""),
        "TO" => array("name" => "Tonga", "capital" => "Nuku'alofa"),
        "TT" => array("name" => "Trinidad and Tobago", "capital" => "Port of Spain"),
        "TN" => array("name" => "Tunisia", "capital" => "Tunis"),
        "TR" => array("name" => "Turkey", "capital" => "Ankara"),
        "TM" => array("name" => "Turkmenistan", "capital" => "Ashgabat"),
        "TC" => array("name" => "Turks and Caicos Islands", "capital" => "Cockburn Town"),
        "TV" => array("name" => "Tuvalu", "capital" => "Funafuti"),
        "UG" => array("name" => "Uganda", "capital" => "Kampala"),
        "UA" => array("name" => "Ukraine", "capital" => "Kiev"),
        "AE" => array("name" => "United Arab Emirates", "capital" => "Abu Dhabi"),
        "GB" => array("name" => "United Kingdom", "capital" => "London"),
        "US" => array("name" => "United States", "capital" => "Washington"),
        "UM" => array("name" => "United States Minor Outlying Islands", "capital" => ""),
        "UY" => array("name" => "Uruguay", "capital" => "Montevideo"),
        "UZ" => array("name" => "Uzbekistan", "capital" => "Tashkent"),
        "VU" => array("name" => "Vanuatu", "capital" => "Port Vila"),
        "VE" => array("name" => "Venezuela", "capital" => "Caracas"),
        "VN" => array("name" => "Viet Nam", "capital" => "Hanoi"),
        "VG" => array("name" => "Virgin Islands, British", "capital" => "Road Town"),
        "VI" => array("name" => "Virgin Islands, U.s.", "capital" => "Charlotte Amalie"),
        "WF" => array("name" => "Wallis and Futuna", "capital" => "Mata Utu"),
        "EH" => array("name" => "Western Sahara", "capital" => "El-Aaiun"),
        "YE" => array("name" => "Yemen", "capital" => "Sanaa"),
        "ZM" => array("name" => "Zambia", "capital" => "Lusaka"),
        "ZW" => array("name" => "Zimbabwe", "capital" => "Harare")
    ],

    'state_list' => [
        "AL" => array("name" => "ALABAMA"),
        "AK" => array("name" => "ALASKA"),
        "AS" => array("name" => "AMERICAN SAMOA"),
        "AZ" => array("name" => "ARIZONA"),
        "AR" => array("name" => "ARKANSAS"),
        "CA" => array("name" => "CALIFORNIA"),
        "CO" => array("name" => "COLORADO"),
        "CT" => array("name" => "CONNECTICUT"),
        "DE" => array("name" => "DELAWARE"),
        "DC" => array("name" => "DISTRICT OF COLUMBIA"),
    ],

    $states = array(
        'FM'=>'FEDERATED STATES OF MICRONESIA',
        'FL'=>'FLORIDA',
        'GA'=>'GEORGIA',
        'GU'=>'GUAM GU',
        'HI'=>'HAWAII',
        'ID'=>'IDAHO',
        'IL'=>'ILLINOIS',
        'IN'=>'INDIANA',
        'IA'=>'IOWA',
        'KS'=>'KANSAS',
        'KY'=>'KENTUCKY',
        'LA'=>'LOUISIANA',
        'ME'=>'MAINE',
        'MH'=>'MARSHALL ISLANDS',
        'MD'=>'MARYLAND',
        'MA'=>'MASSACHUSETTS',
        'MI'=>'MICHIGAN',
        'MN'=>'MINNESOTA',
        'MS'=>'MISSISSIPPI',
        'MO'=>'MISSOURI',
        'MT'=>'MONTANA',
        'NE'=>'NEBRASKA',
        'NV'=>'NEVADA',
        'NH'=>'NEW HAMPSHIRE',
        'NJ'=>'NEW JERSEY',
        'NM'=>'NEW MEXICO',
        'NY'=>'NEW YORK',
        'NC'=>'NORTH CAROLINA',
        'ND'=>'NORTH DAKOTA',
        'MP'=>'NORTHERN MARIANA ISLANDS',
        'OH'=>'OHIO',
        'OK'=>'OKLAHOMA',
        'OR'=>'OREGON',
        'PW'=>'PALAU',
        'PA'=>'PENNSYLVANIA',
        'PR'=>'PUERTO RICO',
        'RI'=>'RHODE ISLAND',
        'SC'=>'SOUTH CAROLINA',
        'SD'=>'SOUTH DAKOTA',
        'TN'=>'TENNESSEE',
        'TX'=>'TEXAS',
        'UT'=>'UTAH',
        'VT'=>'VERMONT',
        'VI'=>'VIRGIN ISLANDS',
        'VA'=>'VIRGINIA',
        'WA'=>'WASHINGTON',
        'WV'=>'WEST VIRGINIA',
        'WI'=>'WISCONSIN',
        'WY'=>'WYOMING',
        'AE'=>'ARMED FORCES AFRICA \ CANADA \ EUROPE \ MIDDLE EAST',
        'AA'=>'ARMED FORCES AMERICA (EXCEPT CANADA)',
        'AP'=>'ARMED FORCES PACIFIC'
    ),
];

